---
title: "How to create ensemble files with ProsodyPro 6.1.4 beta"
author: "Kevin L. Penner"
date: "11/2/2016"
output: html_document
---

## Introduction

Use this document to help you to create ensemble files with ***\_ProsodyPro6.1.4\_beta\_extract.praat*** after you have finished the annotation of all tokens in the large ```.wav``` file containing all experiment tokens.[^1] Yi Xu created this version of the script for me which creates individual sound files for each token in the large file. This is necessary in order to allow for compensation in cases where an item was recorded out of order (e.g. B1 recorded before finishing all A items: A1, A2, A3, A4, A5, A6, A7, ***B1***, A8, B2, B3, B4, B5, B6, B7, B8,…) and to allow "across speaker" averaging because it allows the items to be processed in the order of their file names. Xu also recommends using the latest non-beta version to do the processing since this version has more features and can do the average across speakers properly. The major difference in usage of that script is that you need to run it in the folder *above* the individual speaker folders. The speaker folder file should contain just the folder names, one per line.


[^1]: Processing data in one large file (rather than separate sound files for each token in the experiment) became possible in ProsodyPro 6 beta.

## Instructions

*Prerequisites:* Each speaker's files must be in a separate folder (directory) named with their 3 initials (which will be added to the dataframes created as the sp(eaker) variable. All speaker folders (directories) must be in the same enclosing folder (directory) which must be manually assigned to sp.dir before running the script

1. Run the script with **Task 3: Process all sentences** selected and **Keep sentences in recording** checked
  + This creates individual sound files for each item
  + **Note: You should see windows opening and closing as it runs through each annotated item. This takes several minutes and should end with the main script window closing (you'll get the spinning beach ball with no apparent activity for a while before it closes).**
  + Watch for error messages saying that there were no annotations for a file
  + If you have to redo this step, delete all the sound files that were created because the script will try to process them too (or you can, probably, just ignore the error message)
2. Open the latest non-beta script for processing individual sound files (***\_ProsodyPro\_5.6.1.praat***), and run **Task 3:Get ensemble files*** with **Nrepetitions = 8** (if there all items have 8 reps), otherwise create a repetition list and check **Use repetition list**
  + This will calculate the averages for each item based on the file names disregarding the integer at the end of each file name
  + A window will appear with a list of each file as it is processed and ends with a list of the 30 ensemble files it has created.
  + All ProsodyPro "ensemble" output files are `.txt` files (e.g. mean_normf0.txt, maxf0.txt, minf0.txt, etc.)
  + ALTERNATIVELY, Run the old script (***\_ProsodyPro6.1.3\_beta.praat***) again with **Task 4: Get ensemble files** and **Keep sentences in recording** unchecked and **Nrepetitions = 8**
  
> *Note:* Be sure that the *NRepetitions:* box is set to the number of repetitions for **every** experiment item. To average across unequal number of repetitions, check the [ ] *Use repetition list* box and then create a repetition list and save it in the directory as repetition_list.txt. In this file sound-file names are listed in a single column, with blank lines separating the repetition groups. You can create this file by renaming "FileList.txt" that is always generated by ProsodyPro, and then modifying it by inserting blank lines and deleting sounds that you want to exclude. Note that deleting sound names in this file allows you to skip sounds that you want to exclude in your final analysis. 

> **In order to create the file list of all of the individual .wav files you will need to run ProsodyPro once on the segmented files** (i.e. without **Keep sentences in recording** checked (or with the version of ProsodyPro that works only on segmented files). This can be done with the **Get ensemble files** task even those these ensemble files will not be used.

3. Calculating across speaker average...


