---
title: "N-Pron Data Processing"
author: "Kevin L. Penner"
date: "February 3, 2016"
output: html_document
---

***
# Introduction
***

This document describes the process of getting the N-Pron experiment (Novermber 29, 2014) data (i.e. the ProsodyPro output) into R and begin processing, visualizing and doing analysis with it.



***
# Get the data into R
***

Run the script `get_ensemble_files.R` with the path to the directory containing the folders for the individual speaker's data for the N-Pron experiment assigned to the variable `sp.dir`. This script will create the list ```dataset.list```, which has a separate list item for each type ensemble file (e.g. ```duration```, ```normf0```, ```mean_normf0```, etc). Each list item has the all the data from ensemble file of that type for each speaker. So, the ```duration``` list item contains all the duration data from each speaker in the experiment stored in a dataframe.


***
# Plotting `mean_normf0` dataset
***

## Explore the `mean_normf0` dataset and copying it to ```dat```

Extract the `mean_normf0` data to `dat` for safer and easier processing:
```
dataset.list[['mean_normf0']] -> dat
```

Explore `dat`:
```
str(dat)
```

Look at the first 8 observations:
```
head(dat)
```

Find the different speakers:
```
unique(dat$sp)
```

## Add extra variables to the `mean_normf0` dataset

### Add a variable for the noun of each item

```
noun <- gsub("_(.*)_de_(.*)_","\\1", dat$Normtime) # extract the noun from the filename in the                                                         Normtime variable
dat$noun <- noun
table(dat$noun) # inspect
```

### Add a variable for the pronoun of each item

```
pron <- gsub("_(.*)_de_(.*)_","\\2", dat$Normtime) # extract the pronoun from the filename
dat$pron <- pron
table(dat$pron) # inspect
```

### Add variables for the Mixtec word and tone melody of each item

#### Read in list of nouns with melodies

```
npron.melody.list <- read.table(file.choose(), header=T, sep="\t", encoding="UTF-8")
npron.melody.list
str(npron.melody.list)
```

#### Convert gloss, mixtec and melody variables from factors to character strings

```
for (i in 2:4) {
  npron.melody.list[,i] <- as.character(npron.melody.list[,i])
}
```

#### Copy ```dat$noun``` to new variables ```dat$mix``` and ```dat$mel```

```
dat$mix <- dat$noun
dat$mel <- dat$noun
```

#### Substitue the proper Mixtec word and melody from ```npron.melody.list``` for each noun in ```dat$mix``` and ```dat$mel```

```
for (i in 1:nrow(npron.melody.list)) { 
  dat[dat$mix==npron.melody.list[i,]$g,]$mix <- npron.melody.list[i,]$mix
  dat[dat$mel==npron.melody.list[i,]$g,]$mel <- npron.melody.list[i,]$mel
}
```

#### Check the melodies & glosses

```
names(dat)
dat[,c(1,32:36)]
```


## Plotting the `mean_normf0` dataset

Run the script ```N-Pron_plot_by_speaker.R```. This will plot all the pronouns for each noun on a single plot for each speaker.



***
# Plotting `normf0` data
***

## Exploring the `normf0` dataset

Extract the `normf0` data to `dat` for easier processing:
```
dataset.list[['normf0']] -> dat
```

Explore `dat`:
```
str(dat)
```

Look at the first 8 observations:
```
head(dat)
```

Find the different speakers:
```
unique(dat$sp)
```

## Adding extra variables to the `normf0` dataset

### Adding the wordlist item as a variable

Extract the wordlist item from the Normtime variable (which contains the filename), stripping off the leading "_" and trailing "_" and digit:

```
item <- substr(dat$Normtime, 2, nchar(dat$Normtime)-2)
table(item)
dat$item <- item
```

### Adding the repetition number

Extract the repetition number for each observation from the Normtime variable (the final digit in Normtime):
```
num <- substr(dat$Normtime, nchar(dat$Normtime), nchar(dat$Normtime))
table(num)
dat$num <- num
```
